### ISSUE TITLE
poetry.lock is not consistent with pyproject.toml

### ISSUE THREAD

**Issue by paketb0te** [mivanit/dep-graph-viz#1]
Hey, when trying to install I get a warning from poetry:

`Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.`

Running a simple `poetry lock` fixes the issue for me, thought you might want to update here as well :)

**Comment by mivanit** [comment]
Thank you for noticing this and letting me know! Should be fixed as of [56ef507](https://github.com/mivanit/dep-graph-viz/commit/56ef507f407cb71e87f031f6dd1681c7bb893aa7)
